# Example tedge-oscar configuration (TOML format)

# Directory where pulled OCI images will be stored
image_dir = "./images"

# You can also use JSON or YAML formats if preferred.
# For JSON, use: { "image_dir": "./images" }
# For YAML, use: image_dir: ./images
