#!/bin/sh
set -e

EXIT_OK=0
EXIT_USAGE=1
EXIT_FAILURE=2
# EXIT_RETRY=3

usage() {
    cat << EOF
USAGE
    tedge flows plugin for thin-edge.io

    $0 <COMMAND> [MODULE_NAME] [--module-version [VERSION]] [--file [FILE]]

    $0 list
    $0 prepare
    $0 install <MODULE_NAME> [--module-version [VERSION]] [--file [FILE]]
    $0 remove <MODULE_NAME> [--module-version [VERSION]]
    $0 finalize
EOF
}

MODULE_NAME=
MODULE_VERSION=
FILE=

log() { echo "$@" >&2; }

if [ $# -lt 1 ]; then
    log "Invalid number of positional arguments"
    usage
    exit "$EXIT_USAGE"
fi

# argument parsing
while [ $# -gt 0 ]; do
  case "$1" in
    --module-version)
        MODULE_VERSION="$2"
        shift
        ;;
    --file)
        FILE="$2"
        shift
        ;;
    -h|--help)
        usage
        exit "$EXIT_USAGE"
        ;;
    --*|-*)
        log "Unknown option $1"
        exit "$EXIT_USAGE"
        ;;
    *)
        if [ -z "$COMMAND" ]; then
            COMMAND="$1"
        elif [ -z "$MODULE_NAME" ]; then
            MODULE_NAME="$1"
        fi
      ;;
  esac
  shift
done

case "$COMMAND" in
    prepare)
        ;;
    list)
        if ! command -V tedge-oscar >/dev/null 2>&1; then
            log "tedge-oscar is not installed"
            exit "$EXIT_USAGE"
        fi

        tedge-oscar flows instances list -o tsv --select name,imageVersion
        ;;
    install)
        if [ -n "$FILE" ]; then
            log "Installing from file: $FILE"
            tedge-oscar flows images load "$FILE" || exit "$EXIT_FAILURE"
        else
            log "Pulling flow image: $MODULE_VERSION"
            tedge-oscar flows images pull "$MODULE_VERSION" || exit "$EXIT_FAILURE"
        fi

        log "Deploying instance. name=$MODULE_NAME, image=$MODULE_VERSION"
        tedge-oscar flows instances deploy "$MODULE_NAME" "$MODULE_VERSION" || exit "$EXIT_FAILURE"
        ;;
    remove)
        # Removing
        tedge-oscar flows instances remove "$MODULE_NAME" || exit "$EXIT_FAILURE"
        ;;
    update-list)
        # Not supported, use remove install and remove instead
        exit "$EXIT_USAGE"
        ;;
    finalize)
        ;;
    *)
        log "Unsupported command: $COMMAND"
        exit 1
        ;;
esac

exit "$EXIT_OK"
